### ISSUE TITLE
Synology RS816

### ISSUE THREAD

**Issue by dragon2611** [zerotier/ZeroTierNAS#6] opened 2017-11-17 15:10 UTC
Any possibility of supporting a synology RS816 at the moment it looks like ZeroTier chews up about 40% cpu and just loads a grey window when opening up the webapp

![untitled](https://user-images.githubusercontent.com/6185399/32953886-76e00fe0-cba9-11e7-8251-0fd6eb0a2302.png)

**Comment by joseph-henry** [comment] 2017-11-17 19:38
Thanks for bringing this to our attention. We've had one other report of this. I'll try to have a solution soon.

**Comment by dragon2611** [comment] 2017-11-25 14:12
Do you have an estimate of how long that will take, if it's going to be a while I might try installing the debian chroot and installing the zerotier package there as I've heard that one works and I don't actually need the gui element.

**Comment by thunfischbrot** [comment] 2017-11-28 10:45
Is this a duplicate of https://github.com/zerotier/ZeroTierNAS/issues/3 ?

**Comment by dragon2611** [comment] 2017-11-28 16:29
Probably, not sure if those models have the same CPU family without researching it.

**Comment by joseph-henry** [comment] 2017-12-04 23:48
I've got some beta packages you guys can try out:

For the RS816 which uses the Marvell Armada 385 88F6820: https://download.zerotier.com/dist/zerotier-1.2.4-syn-armada38x-6.1.spk

@thunfischbrot Check ticket #3 for relevant packages for those threads.

Let me know if these work for you guys.

Thanks.

**Comment by dragon2611** [comment] 2017-12-05 09:33
Seems to work although I'm not sure managed routes get pushed (or I've set them up wrong)
My other devices on that network are exchanging routes via OSPF but of course the synology doesn't support that out of the box

**Comment by joseph-henry** [comment] 2017-12-05 09:36
Routes are tricky on Synology devices, we've had issues before but it seemed we had resolved that. I'll test the route pushing tomorrow.

**Comment by dragon2611** [comment] 2017-12-05 09:45
I've added a static route manually which seems to work, not sure if it will stay active following a reboot but then again that particular unit probably won't be getting rebooted very often.

I'd ended up using SSHFS over the WAN in the absence of a decent VPN option (It's firewalled to set of specific hosts) and that seems faster than SMB/CIFS over ZT but at least now I have the option of using those if connecting say a windows client.

**Comment by joseph-henry** [comment] 2018-02-16 20:36
Going to close this ticket as I believe we've fixed the primary issue. If you are still having issues with your routes feel free to open a new ticket.

**Closed by joseph-henry** 2018-02-16 20:36 UTC
Labels: bug
